name: 'vcpkg-builder'
description: 'VCPKG packages builder with output in artifact.'

inputs:
  packages:  # id of input
    description: 'IDs of packages to download'
    required: true

  artifact-id:
    description: 'ID for artifact to be published (name of runner is added automatically)'
    required: true

runs:
  using: composite
  steps:
  
    - name: main-action
      uses: index.js
      with:
        out-package-id: ${{ inputs.packages }}

    - uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.artifact-id }}-${{ runner.os }}
        path: /vcpkg/