name: 'vcpkg-builder'
description: 'VCPKG packages builder with output in artifact.'

inputs:
  packages:
    description: 'IDs of packages to download (strings separated by semicolon)'
    required: true

  artifact-id:
    description: 'ID for artifact to be published (name of runner is added automatically)'
    required: true

runs:
  using: composite
  steps:
  
    - name: Install
      shell: sh
      run: "cmake -Dlibraries='${{ inputs.packages }}' ."

    - uses: actions/upload-artifact@v3
      if: ${{ runner.os != 'Linux' }}
      with:
        name: ${{ inputs.artifact-id }}-${{ runner.os }}
        path: vcpkg
        
    - uses: actions/upload-artifact@v3
      if: ${{ runner.os == 'Linux' }}
      with:
        name: ${{ inputs.artifact-id }}-${{ runner.os }}
        path: /usr/local/share/vcpkg
