# This is a basic workflow to help you get started with Actions

name: Action test

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    
    strategy:
      matrix:
        runsOn: ['linux-latest', 'windows-latest', 'macOs-latest']
   
    # The type of runner that the job will run on
    runs-on: ${{ matrix.runsOn }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3  
      
      - uses: mateuszokroj1/VCPKG-package-builder@v1.0.2
        with:
          packages: gtest;opengl
          artifact-id: abcd